//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMaxApi.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewMaxApi.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The string should not be empty or consist only of spaces..
        /// </summary>
        internal static string CallbackRegexError {
            get {
                return ResourceManager.GetString("CallbackRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The string must be an integer that can start with a minus sign (for negative numbers) or without a sign (for positive numbers), after the sign (if any) only numbers (0-9) must go, other characters (letters, spaces, dots, commas, etc.) are not allowed..
        /// </summary>
        internal static string ChatIdRegexError {
            get {
                return ResourceManager.GetString("ChatIdRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The string must begin with an optional @ character, followed by at least one letter (Latin). Letters, numbers, hyphens (-), or underscores (_) can be used after the first letter..
        /// </summary>
        internal static string ChatLinkRegexError {
            get {
                return ResourceManager.GetString("ChatLinkRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} parameter must be greater than the {1} parameter..
        /// </summary>
        internal static string FromToError {
            get {
                return ResourceManager.GetString("FromToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The string must contain only Latin letters, numbers, underscores (_) or hyphens (-), and must not be shorter than one character..
        /// </summary>
        internal static string MessageRegexError {
            get {
                return ResourceManager.GetString("MessageRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} parameter not specified..
        /// </summary>
        internal static string ParameterNotSpecified {
            get {
                return ResourceManager.GetString("ParameterNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} parameter must be in the range from {1} to {2}..
        /// </summary>
        internal static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The string must consist only of Latin letters (A-Z, a-z), numbers (0-9), hyphens (-) and underscores (_), must be between 5 and 256 characters long, and must not contain spaces or special characters. (!@#$%^&amp;*), Cyrillic or other characters other than those allowed..
        /// </summary>
        internal static string SecretRegexError {
            get {
                return ResourceManager.GetString("SecretRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred when sending the request. Reason: &apos;{0}&apos;. Status code: {1}..
        /// </summary>
        internal static string SendingRequestError {
            get {
                return ResourceManager.GetString("SendingRequestError", resourceCulture);
            }
        }
    }
}
